package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// Phase constants — the three states of the state machine
const (
	PhaseProvisioning = "Provisioning" // PVC being created / waiting for Bound
	PhaseDownloading  = "Downloading"  // Job running to populate PVC
	PhaseReady        = "Ready"        // Deployment pods running
	PhaseFailed       = "Failed"       // something went wrong
)

// ModelDeployment is the Schema for the modeldeployments API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type ModelDeployment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ModelDeploymentSpec   `json:"spec,omitempty"`
	Status ModelDeploymentStatus `json:"status,omitempty"`
}

// ModelDeploymentSpec defines the desired state
type ModelDeploymentSpec struct {
	// ModelName is the model identifier, e.g. "meta-llama/Meta-Llama-3-8B-Instruct"
	ModelName string `json:"modelName"`

	// Replicas is the number of inference pods to run
	// +kubebuilder:default=1
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=8
	Replicas int32 `json:"replicas"`

	// StorageSize is the PVC size for the model cache, e.g. "10Gi"
	StorageSize string `json:"storageSize"`

	// GPUPerPod is the number of GPUs to request per inference pod
	// +kubebuilder:default=1
	GPUPerPod int32 `json:"gpuPerPod"`

	// StorageClass is the K8s StorageClass for the PVC
	// Defaults to "standard" (works on kind)
	// +kubebuilder:default="standard"
	StorageClass string `json:"storageClass,omitempty"`
}

// ModelDeploymentStatus defines the observed state
type ModelDeploymentStatus struct {
	// Phase is the current state: Provisioning | Downloading | Ready | Failed
	Phase string `json:"phase,omitempty"`

	// ReadyReplicas is how many inference pods are currently Running
	ReadyReplicas int32 `json:"readyReplicas"`

	// Message is a human-readable description of the current state
	Message string `json:"message,omitempty"`

	// Conditions follow the standard K8s condition pattern
	Conditions []metav1.Condition `json:"conditions,omitempty"`

	// PVCName is the name of the created PVC
	PVCName string `json:"pvcName,omitempty"`

	// DownloadJobName is the name of the download Job
	DownloadJobName string `json:"downloadJobName,omitempty"`

	// DeploymentName is the name of the inference Deployment
	DeploymentName string `json:"deploymentName,omitempty"`
}

// ModelDeploymentList contains a list of ModelDeployment
// +kubebuilder:object:root=true
type ModelDeploymentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ModelDeployment `json:"items"`
}

// --- DeepCopy methods (normally generated by controller-gen) ---

func (in *ModelDeployment) DeepCopyInto(out *ModelDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ModelDeployment) DeepCopy() *ModelDeployment {
	if in == nil {
		return nil
	}
	out := new(ModelDeployment)
	in.DeepCopyInto(out)
	return out
}

func (in *ModelDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ModelDeploymentList) DeepCopyInto(out *ModelDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ModelDeploymentList) DeepCopy() *ModelDeploymentList {
	if in == nil {
		return nil
	}
	out := new(ModelDeploymentList)
	in.DeepCopyInto(out)
	return out
}

func (in *ModelDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ModelDeploymentSpec) DeepCopyInto(out *ModelDeploymentSpec) {
	*out = *in
}

func (in *ModelDeploymentStatus) DeepCopyInto(out *ModelDeploymentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}
